name: Build Android CMake for Win

on:
  push:
    tags:
      - v*
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
    - name: Fetch OpenSSL
      run: |
        git clone https://github.com/KDAB/android_openssl.git ../android_openssl
    - uses: actions/checkout@v2
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        target: 'android'
        arch: 'android'
        version: '5.15.1'
        modules: 'qtcharts qtwebengine qtscript'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
    - name: Configure
      run: |
        cmake . \
          -DCMAKE_FIND_ROOT_PATH=$Qt5_DIR \
          -DCMAKE_PREFIX_PATH=$Qt5_DIR \
          -DQT_QMAKE_EXECUTABLE=$Qt5_DIR/bin/qmake.exe
    - name: Compile
      run: |
        pwd
        make
        # make install
        make apk
    - name: show filetrees
      run: |
        ls -R
    - uses: actions/upload-artifact@v1
      with:
        name: Debug-APK
        path: android-build/build/outputs/apk/debug/android-build-debug.apk
