name: Build for Android CMake

on:
  push:
    tags:
      - v*
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        mkdir $PWD/android-build/build/outputs/apk/debug/android-build-debug/lib/armeabi-v7a
        cp libcrypto_1_1.so libssl_1_1.so $PWD/android-build/build/outputs/apk/debug/android-build-debug/lib/armeabi-v7a/
        ls . -R
